export type ScaleType = 'A' | 'B'; // A = real-world numeric, B = psychological 1–10

export interface Question {
  id: string;
  label: string;
  description: string;
  tooltip: string;
  min: number;
  max: number;
  step: number;
  unit: string;
  scaleType: ScaleType;
  optimalMin: number;
  optimalMax: number;
  defaultValue: number;
  higherIsBetter: boolean;
}

export interface Category {
  id: string;
  title: string;
  icon: string;
  description: string;
  questions: Question[];
}

export const categories: Category[] = [
  {
    id: 'growth',
    title: '1. Growth & Effort',
    icon: '🚀',
    description: 'How much energy are you investing in your actual development?',
    questions: [
      {
        id: 'g1',
        label: 'Focused Study / Work Hours',
        description: 'Average hours of focused study or deep skill work per day',
        tooltip: '6–8 hrs is elite. Above 10 hrs risks burnout with diminishing returns.',
        min: 0, max: 12, step: 0.5,
        unit: 'hrs/day',
        scaleType: 'A',
        optimalMin: 6, optimalMax: 8,
        defaultValue: 4,
        higherIsBetter: true,
      },
      {
        id: 'g2',
        label: 'Deep Work Ability',
        description: 'Hours of truly uninterrupted, cognitively demanding work per day',
        tooltip: '3–4 hrs of genuine deep work is elite. 5+ hrs yields diminishing returns.',
        min: 0, max: 6, step: 0.5,
        unit: 'hrs/day',
        scaleType: 'A',
        optimalMin: 3, optimalMax: 4,
        defaultValue: 2,
        higherIsBetter: true,
      },
      {
        id: 'g3',
        label: 'Daily Productivity Rate',
        description: 'What % of your work time produces genuine output?',
        tooltip: 'The average person is only productive ~30% of their time. 65%+ is strong.',
        min: 0, max: 100, step: 5,
        unit: '%',
        scaleType: 'A',
        optimalMin: 60, optimalMax: 85,
        defaultValue: 40,
        higherIsBetter: true,
      },
      {
        id: 'g4',
        label: 'Time Waste (Daily)',
        description: 'Hours spent on genuinely low-value, unproductive activity',
        tooltip: '0–2 hrs is healthy. More than 4 hrs severely erodes your life output.',
        min: 0, max: 10, step: 0.5,
        unit: 'hrs/day',
        scaleType: 'A',
        optimalMin: 0, optimalMax: 2,
        defaultValue: 4,
        higherIsBetter: false,
      },
      {
        id: 'g5',
        label: 'Learning Consistency',
        description: 'How consistently do you expose yourself to new knowledge each week?',
        tooltip: 'Daily learners compound knowledge 10× faster over a 5-year span.',
        min: 1, max: 10, step: 1,
        unit: '/10',
        scaleType: 'B',
        optimalMin: 7, optimalMax: 10,
        defaultValue: 5,
        higherIsBetter: true,
      },
      {
        id: 'g6',
        label: 'Skill-Building Frequency',
        description: 'How often do you do deliberate practice on high-value skills?',
        tooltip: 'Deliberate practice (not passive learning) is what actually creates expertise.',
        min: 1, max: 10, step: 1,
        unit: '/10',
        scaleType: 'B',
        optimalMin: 7, optimalMax: 10,
        defaultValue: 5,
        higherIsBetter: true,
      },
      {
        id: 'g7',
        label: 'Commitment Level',
        description: 'Your dedication to long-term goals even when motivation is low',
        tooltip: 'Commitment is what separates goal-setters from goal-achievers.',
        min: 1, max: 10, step: 1,
        unit: '/10',
        scaleType: 'B',
        optimalMin: 7, optimalMax: 10,
        defaultValue: 5,
        higherIsBetter: true,
      },
      {
        id: 'g8',
        label: 'Execution Speed',
        description: 'How quickly do you turn decisions and ideas into real action?',
        tooltip: 'Speed of execution is often more valuable than perfection.',
        min: 1, max: 10, step: 1,
        unit: '/10',
        scaleType: 'B',
        optimalMin: 7, optimalMax: 10,
        defaultValue: 5,
        higherIsBetter: true,
      },
    ],
  },
  {
    id: 'discipline',
    title: '2. Discipline & Habits',
    icon: '⚡',
    description: 'Your behavioral consistency and habit infrastructure',
    questions: [
      {
        id: 'd1',
        label: 'Procrastination Resistance',
        description: '1 = You constantly delay. 10 = You execute immediately.',
        tooltip: 'Procrastination is the #1 cause of life regret. A +2 shift here yields outsized results.',
        min: 1, max: 10, step: 1,
        unit: '/10',
        scaleType: 'B',
        optimalMin: 7, optimalMax: 10,
        defaultValue: 5,
        higherIsBetter: true,
      },
      {
        id: 'd2',
        label: 'Distraction Resistance',
        description: '1 = Easily distracted. 10 = Laser-focused for hours.',
        tooltip: 'Each distraction costs ~23 minutes of full refocus time on average.',
        min: 1, max: 10, step: 1,
        unit: '/10',
        scaleType: 'B',
        optimalMin: 7, optimalMax: 10,
        defaultValue: 5,
        higherIsBetter: true,
      },
      {
        id: 'd3',
        label: 'Routine Consistency',
        description: 'How strictly do you follow your planned daily schedule?',
        tooltip: 'Strong routines reduce decision fatigue and auto-compound good habits.',
        min: 1, max: 10, step: 1,
        unit: '/10',
        scaleType: 'B',
        optimalMin: 7, optimalMax: 10,
        defaultValue: 5,
        higherIsBetter: true,
      },
      {
        id: 'd4',
        label: 'Sleep Hours',
        description: 'Average hours of sleep per night',
        tooltip: '7–8 hrs is scientifically optimal. Both under and over-sleeping impairs cognition.',
        min: 0, max: 12, step: 0.5,
        unit: 'hrs/night',
        scaleType: 'A',
        optimalMin: 7, optimalMax: 8,
        defaultValue: 7,
        higherIsBetter: true,
      },
      {
        id: 'd5',
        label: 'Self-Control',
        description: 'Ability to resist short-term temptations for long-term gain',
        tooltip: 'Self-control is the single best predictor of long-term life outcomes in research.',
        min: 1, max: 10, step: 1,
        unit: '/10',
        scaleType: 'B',
        optimalMin: 7, optimalMax: 10,
        defaultValue: 5,
        higherIsBetter: true,
      },
      {
        id: 'd6',
        label: 'Follow-Through Rate',
        description: 'How often do you fully complete what you commit to starting?',
        tooltip: 'Finishing what you start builds identity-level discipline over time.',
        min: 1, max: 10, step: 1,
        unit: '/10',
        scaleType: 'B',
        optimalMin: 7, optimalMax: 10,
        defaultValue: 5,
        higherIsBetter: true,
      },
      {
        id: 'd7',
        label: 'Time Management',
        description: 'How efficiently do you allocate and protect your time?',
        tooltip: 'Elite performers treat their calendar as a strategic, irreplaceable asset.',
        min: 1, max: 10, step: 1,
        unit: '/10',
        scaleType: 'B',
        optimalMin: 7, optimalMax: 10,
        defaultValue: 5,
        higherIsBetter: true,
      },
    ],
  },
  {
    id: 'direction',
    title: '3. Direction & Clarity',
    icon: '🧭',
    description: 'How well-defined is your path, purpose, and strategic direction?',
    questions: [
      {
        id: 'c1',
        label: 'Career / Life Clarity',
        description: 'How clear are you about what you want and where you are going?',
        tooltip: 'Clarity of direction multiplies the impact of every other effort you make.',
        min: 1, max: 10, step: 1,
        unit: '/10',
        scaleType: 'B',
        optimalMin: 7, optimalMax: 10,
        defaultValue: 5,
        higherIsBetter: true,
      },
      {
        id: 'c2',
        label: 'Long-Term Vision',
        description: 'Clarity and strength of your 5–10 year life vision',
        tooltip: 'People with a vivid 5-year vision make dramatically better daily decisions.',
        min: 1, max: 10, step: 1,
        unit: '/10',
        scaleType: 'B',
        optimalMin: 7, optimalMax: 10,
        defaultValue: 5,
        higherIsBetter: true,
      },
      {
        id: 'c3',
        label: 'Goal Setting & Review',
        description: 'How actively do you set, write, and review clear goals?',
        tooltip: 'Written goals are 42% more likely to be achieved than unwritten ones.',
        min: 1, max: 10, step: 1,
        unit: '/10',
        scaleType: 'B',
        optimalMin: 7, optimalMax: 10,
        defaultValue: 5,
        higherIsBetter: true,
      },
      {
        id: 'c4',
        label: 'Strategic Thinking',
        description: 'Ability to think multiple steps ahead and plan non-linearly',
        tooltip: 'Strategic thinkers solve tomorrow\'s problems before they arrive.',
        min: 1, max: 10, step: 1,
        unit: '/10',
        scaleType: 'B',
        optimalMin: 7, optimalMax: 10,
        defaultValue: 5,
        higherIsBetter: true,
      },
      {
        id: 'c5',
        label: 'Risk Tolerance',
        description: 'Comfort level with taking calculated, high-upside risks',
        tooltip: 'Moderate-high risk tolerance (6–8) correlates with the greatest long-term gains.',
        min: 1, max: 10, step: 1,
        unit: '/10',
        scaleType: 'B',
        optimalMin: 6, optimalMax: 9,
        defaultValue: 5,
        higherIsBetter: true,
      },
      {
        id: 'c6',
        label: 'Goal-Action Alignment',
        description: 'Do your daily actions genuinely reflect your stated goals?',
        tooltip: 'Misalignment between goals and daily action is the core engine of regret.',
        min: 1, max: 10, step: 1,
        unit: '/10',
        scaleType: 'B',
        optimalMin: 7, optimalMax: 10,
        defaultValue: 5,
        higherIsBetter: true,
      },
      {
        id: 'c7',
        label: 'Adaptability',
        description: 'How quickly and effectively do you pivot when circumstances change?',
        tooltip: 'Adaptability is the most critical skill in a rapidly changing environment.',
        min: 1, max: 10, step: 1,
        unit: '/10',
        scaleType: 'B',
        optimalMin: 7, optimalMax: 10,
        defaultValue: 5,
        higherIsBetter: true,
      },
    ],
  },
  {
    id: 'finance',
    title: '4. Financial Behavior',
    icon: '💰',
    description: 'Your financial discipline and wealth-building behaviour',
    questions: [
      {
        id: 'f1',
        label: 'Savings Rate',
        description: 'What % of your income do you consistently save or invest?',
        tooltip: '20–40% savings rate is the strongest zone. 0% = high financial regret risk.',
        min: 0, max: 100, step: 5,
        unit: '%',
        scaleType: 'A',
        optimalMin: 20, optimalMax: 40,
        defaultValue: 15,
        higherIsBetter: true,
      },
      {
        id: 'f2',
        label: 'Spending Intentionality',
        description: '1 = Highly impulsive spending. 10 = Fully intentional & planned.',
        tooltip: 'Intentional spenders build wealth 3× faster than those who spend emotionally.',
        min: 1, max: 10, step: 1,
        unit: '/10',
        scaleType: 'B',
        optimalMin: 7, optimalMax: 10,
        defaultValue: 5,
        higherIsBetter: true,
      },
      {
        id: 'f3',
        label: 'Investment Awareness',
        description: 'Your knowledge and active participation in wealth-building investments',
        tooltip: 'Starting at 25 vs 35 can mean 2–3× more wealth at retirement due to compounding.',
        min: 1, max: 10, step: 1,
        unit: '/10',
        scaleType: 'B',
        optimalMin: 7, optimalMax: 10,
        defaultValue: 5,
        higherIsBetter: true,
      },
      {
        id: 'f4',
        label: 'Financial Planning',
        description: 'How well do you plan for future major financial milestones?',
        tooltip: 'A clear financial plan reduces anxiety and increases goal attainment.',
        min: 1, max: 10, step: 1,
        unit: '/10',
        scaleType: 'B',
        optimalMin: 7, optimalMax: 10,
        defaultValue: 5,
        higherIsBetter: true,
      },
      {
        id: 'f5',
        label: 'Emergency Fund Strength',
        description: 'How robust is your financial safety net (months of expenses covered)?',
        tooltip: 'A 3–6 month emergency fund eliminates financial panic and enables better decisions.',
        min: 1, max: 10, step: 1,
        unit: '/10',
        scaleType: 'B',
        optimalMin: 7, optimalMax: 10,
        defaultValue: 5,
        higherIsBetter: true,
      },
    ],
  },
  {
    id: 'health',
    title: '5. Health & Energy',
    icon: '💪',
    description: 'Your physical and mental health as the foundation for everything else',
    questions: [
      {
        id: 'h1',
        label: 'Physical Activity',
        description: 'Exercise or physical training sessions per week',
        tooltip: '4–6 sessions/week is the optimal zone. More than 10 risks overtraining.',
        min: 0, max: 14, step: 1,
        unit: 'sessions/wk',
        scaleType: 'A',
        optimalMin: 4, optimalMax: 6,
        defaultValue: 3,
        higherIsBetter: true,
      },
      {
        id: 'h2',
        label: 'Energy Levels',
        description: 'Your average daily energy and mental vitality throughout the day',
        tooltip: 'High energy is a multiplier — it amplifies the quality of every hour.',
        min: 1, max: 10, step: 1,
        unit: '/10',
        scaleType: 'B',
        optimalMin: 7, optimalMax: 10,
        defaultValue: 5,
        higherIsBetter: true,
      },
      {
        id: 'h3',
        label: 'Stress Management',
        description: 'Ability to manage and recover from high-pressure situations',
        tooltip: 'Chronic stress silently degrades decision quality, health, and creativity.',
        min: 1, max: 10, step: 1,
        unit: '/10',
        scaleType: 'B',
        optimalMin: 7, optimalMax: 10,
        defaultValue: 5,
        higherIsBetter: true,
      },
      {
        id: 'h4',
        label: 'Sleep Quality',
        description: 'How restful and restorative is your sleep on average?',
        tooltip: 'Sleep quality matters as much as quantity for cognitive performance.',
        min: 1, max: 10, step: 1,
        unit: '/10',
        scaleType: 'B',
        optimalMin: 7, optimalMax: 10,
        defaultValue: 5,
        higherIsBetter: true,
      },
      {
        id: 'h5',
        label: 'Mental Clarity',
        description: 'Your baseline level of mental focus, lack of brain fog',
        tooltip: 'Mental clarity is directly tied to sleep, nutrition, exercise and low stress.',
        min: 1, max: 10, step: 1,
        unit: '/10',
        scaleType: 'B',
        optimalMin: 7, optimalMax: 10,
        defaultValue: 5,
        higherIsBetter: true,
      },
    ],
  },
  {
    id: 'awareness',
    title: '6. Self-Awareness & Mindset',
    icon: '🧠',
    description: 'Your internal intelligence, growth mindset, and self-understanding',
    questions: [
      {
        id: 'p1',
        label: 'Self-Reflection Habit',
        description: 'How often and deeply do you review your progress and decisions?',
        tooltip: 'Regular reflection is the mechanism by which experience becomes wisdom.',
        min: 1, max: 10, step: 1,
        unit: '/10',
        scaleType: 'B',
        optimalMin: 7, optimalMax: 10,
        defaultValue: 5,
        higherIsBetter: true,
      },
      {
        id: 'p2',
        label: 'Growth Mindset',
        description: 'Your belief that abilities are developed through effort and learning',
        tooltip: 'Growth mindset is the strongest predictor of long-term achievement in research.',
        min: 1, max: 10, step: 1,
        unit: '/10',
        scaleType: 'B',
        optimalMin: 7, optimalMax: 10,
        defaultValue: 5,
        higherIsBetter: true,
      },
      {
        id: 'p3',
        label: 'Emotional Intelligence',
        description: 'Understanding and managing your own and others\' emotions effectively',
        tooltip: 'High EQ is consistently linked to better relationships, leadership, and outcomes.',
        min: 1, max: 10, step: 1,
        unit: '/10',
        scaleType: 'B',
        optimalMin: 7, optimalMax: 10,
        defaultValue: 5,
        higherIsBetter: true,
      },
      {
        id: 'p4',
        label: 'Self-Awareness',
        description: 'How clearly do you understand your own strengths, weaknesses, and patterns?',
        tooltip: 'Self-awareness without action is the most painful form of regret.',
        min: 1, max: 10, step: 1,
        unit: '/10',
        scaleType: 'B',
        optimalMin: 7, optimalMax: 10,
        defaultValue: 5,
        higherIsBetter: true,
      },
      {
        id: 'p5',
        label: 'Resilience',
        description: 'How fast and fully do you bounce back from setbacks and failures?',
        tooltip: 'Resilience is not about avoiding failure — it\'s about the speed of recovery.',
        min: 1, max: 10, step: 1,
        unit: '/10',
        scaleType: 'B',
        optimalMin: 7, optimalMax: 10,
        defaultValue: 5,
        higherIsBetter: true,
      },
      {
        id: 'p6',
        label: 'Feedback Acceptance',
        description: 'How openly do you receive and integrate constructive criticism?',
        tooltip: 'Those who seek and use feedback improve 40% faster than those who avoid it.',
        min: 1, max: 10, step: 1,
        unit: '/10',
        scaleType: 'B',
        optimalMin: 7, optimalMax: 10,
        defaultValue: 5,
        higherIsBetter: true,
      },
      {
        id: 'p7',
        label: 'Consistency Mindset',
        description: 'How much do you value and practice showing up every single day?',
        tooltip: 'Consistency over 3 years beats intensity over 3 months, every time.',
        min: 1, max: 10, step: 1,
        unit: '/10',
        scaleType: 'B',
        optimalMin: 7, optimalMax: 10,
        defaultValue: 5,
        higherIsBetter: true,
      },
    ],
  },
];

// Helper: build default slider values map from categories
export function buildDefaultSliders(): Record<string, number> {
  return Object.fromEntries(
    categories.flatMap(c => c.questions.map(q => [q.id, q.defaultValue]))
  );
}

// Helper: get a question by id
export function getQuestionById(id: string): Question | undefined {
  for (const cat of categories) {
    const q = cat.questions.find(q => q.id === id);
    if (q) return q;
  }
  return undefined;
}